---
- name: PLAYBOOK-GET-INTERFACE
  hosts: router-core
  connection: network_cli
  gather_facts: no

  tasks:
    - name: run show version on remote devices
      cisco.iosxr.iosxr_command:
        commands: show version
