---
- name: PLAYBOOK-GET-INTERFACE AND CONFIGURE
  hosts: router_core
  gather_facts: no
  connection: netconf

  tasks:
  # SHOW TASKS
    - name: run show version on remote devices
      cisco.iosxr.iosxr_command:
        commands: 
          - show version
          - show interface brief
  #CONFIG TASKS
    - name: configure top level configuration
      cisco.iosxr.iosxr_config:
        lines: hostname xr1spdl

    - name: configure interface settings
      cisco.iosxr.iosxr_config:
        lines:
        - description test interface
        - ip address 172.31.1.1 255.255.255.0
        parents: interface loopback 1
