---
- name: PLAYBOOK-GET-INTERFACE
  hosts: router-core
  gather_facts: no
  connection: network_cli

  tasks:
    - name: run show version on remote devices
      cisco.iosxr.iosxr_command:
        commands: 
          - show version
          - hostname xr1
