---
- name: play01
  hosts: router-core
  gather_facts: false
  connection: network_cli


  tasks:
    - name: run show version on remote devices
      ansible.netcommon.cli_command:
        command: show version