---
- name: PLAYBOOK-GET-INTERFACE USING PYATS PARSER
  hosts: router-core
  gather_facts: no
  connection: network_cli
  
  tasks:
    - name: "Run command and parse with pyats"
      ansible.utils.cli_parse:
        command: show interfaces
        parser:
          name: ansible.netcommon.pyats
        set_fact: interfaces
