# ansible-playbook -i inventory_host_huawei.yml playbook_for_module_huawei_display_ip_routing_table.yml
- name: PLAYBOOK CONFIG METRO SERVICE HUAWEI
  hosts: metro_access1
  connection: local
  gather_facts: no

  tasks:
    - name: RUN CALL HUAWEI MODULE
      huawei_config:
        command: ["interface GigabitEthernet3/0/1.101", "vlan-type dot1q 101", "mpls l2vc 1.1.1.1 101", "statistic enable", "description ANSIBLE-ACCESS-to-Mikrotik"]
        ansible_host: '{{ hostvars[inventory_hostname].ansible_host }}'
        ansible_network_os: '{{ hostvars[inventory_hostname].ansible_network_os }}'
        ansible_user: '{{ hostvars[inventory_hostname].ansible_user }}'
        ansible_ssh_pass: '{{ hostvars[inventory_hostname].ansible_ssh_pass }}'
        ansible_platform: '{{ hostvars[inventory_hostname].ansible_platform }}'
      register: output

    - name: PRINT OUTPUT SUCCESS MODULE
      debug:
        msg: '{{ output }}'