- name: CloudEngine config test
  hosts: metro_access1
  connection: local
  gather_facts: no
  vars:
    cli:
      host: '{{ hostvars[inventory_hostname].ansible_host }}'
      port: 22
      username: '{{ hostvars[inventory_hostname].ansible_user }}'
      password: '{{ hostvars[inventory_hostname].ansible_ssh_pass }}'
      transport: cli
  tasks:
  - name: "Configure acl configuration and save it"
    community.network.ce_config:
      lines:
        - rule 10 permit source 1.1.1.1 32
        - rule 20 permit source 2.2.2.2 32
        - rule 30 permit source 3.3.3.3 32
        - rule 40 permit source 4.4.4.4 32
        - rule 50 permit source 5.5.5.5 32
      parents: acl 2000
      before: undo acl 2000
      match: exact
      provider: "{{ cli }}"