#  ansible-playbook -i playbook_dds/hosts.yml playbook_dds/005-huawei-undo-l2vc.yml
- name: PLAYBOOK CONFIG METRO SERVICE HUAWEI-2
  hosts: metro_access1
  connection: local
  gather_facts: no

  tasks:
    - name: UNDO MPLS L2VC
      multipolar_huawei_config:
        command: ["interface GigabitEthernet3/0/1.101", "undo vlan-type dot1q 101", "undo mpls l2vc 1.1.1.5 101", "undo statistic enable","quit", "undo interface GigabitEthernet3/0/1.101", "commit"]
        ansible_host: '{{ hostvars[inventory_hostname].ansible_host }}'
        ansible_network_os: '{{ hostvars[inventory_hostname].ansible_network_os }}'
        ansible_user: '{{ hostvars[inventory_hostname].ansible_user }}'
        ansible_ssh_pass: '{{ hostvars[inventory_hostname].ansible_ssh_pass }}'
        ansible_platform: '{{ hostvars[inventory_hostname].ansible_platform }}'
      register: output

    - name: PRINT OUTPUT SUCCESS MODULE
      debug:
        msg: '{{ output }}'