---
pe_router:
  hosts:
    pe_vpn_1:
      ansible_host: 10.14.19.22
      ansible_user: cisco
      ansible_ssh_pass: cisco
      ansible_network_os: iosxr
      ansible_connection: network_cli
      connection: network_cli
      gather_facts: no
      ansible_python_interpreter: auto_silent
    pe_vpn_2:
      ansible_host: 10.14.19.21
      ansible_user: cisco
      ansible_ssh_pass: cisco
      ansible_network_os: iosxr
      ansible_connection: network_cli
      connection: network_cli
      gather_facts: no
      ansible_python_interpreter: auto_silent