---
lab:
  hosts:
    r1:
      ansible_host: 192.168.1.100
      ansible_connection: ssh
      ansible_network_os: cisco.iosxr.iosxr
      ansible_user: cisco
      ansible_password: cisco
      # ansible_python_interpreter: /usr/bin/python3
