---
router_core:
  hosts:
    xr1:
      ansible_host: 192.168.1.100
      ansible_user: cisco
      ansible_ssh_pass: Multip0larHINTP2
      ansible_network_os: iosxr
      ansible_connection: network_cli
      connection: network_cli
      gather_facts: no
      ansible_python_interpreter: auto_silent