---
- name: PLAYBOOK-GET-INTERFACE AND CONFIGURE
  hosts: pe_router
  gather_facts: no
  connection: network_cli

  tasks:
  # SHOW TASKS
    - name: Run show version using iosxr module
      cisco.iosxr.iosxr_command:
        commands: 
          - show version
          - show interface brief