---
- name: PLAYBOOK SHOW VERSION
  hosts: pe_router
  gather_facts: no
  connection: network_cli

  tasks:
  # SHOW TASKS
    - name: run show version on remote devices
      cisco.iosxr.iosxr_command:
        commands: 
          - show version
          - show interface brief