---
- name: PLAYBOOK-GET-INTERFACE AND CONFIGURE
  hosts: pe_router
  gather_facts: no
  connection: network_cli

  tasks:
  # SHOW TASKS
    - name: run show version on remote devices
      ansible.netcommon.cli_command:
        command: show version